# PORT cho Render
server.port=${PORT:8080}

# Database MySQL (Aiven)
spring.datasource.url=jdbc:mysql://mysql-quanlyhoctienganh-trongtriww-d42c.l.aivencloud.com:21917/defaultdb?useSSL=true&requireSSL=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_rvWK3ubOjdLGZDmh_h_

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
